name: thesis-environment

dependencies:
  - python=3.11
  - ipywidgets
  - numpy==1.23.5
  - pyproj
  - geopandas
  - osmnx
  - fiona
  - rtree
  - mapclassify
  - leafmap
  - pip
  - pip:
    - git+https://github.com/wannesm/leuvenmapmatching
    - gpx-converter
    - libspatialindex-dev
