name: thesis-environment

dependencies:
  - python=3.11
  - ipywidgets
  - numpy==1.23.5
  - pyproj
  - -U gpx-converter
  - geopandas
  - leuvenmapmatching
  - osmnx
  - fiona
  - rtree
  - mapclassify
  - leafmap
