name: thesis-environment

dependencies:
  - ipywidgets
  - numpy=1.23.5
  - pyproj
  - geopandas
  - osmnx
  - fiona
  - rtree
  - mapclassify
  - leafmap
  - libspatialindex
  - pip
  - pip:
    - git+https://github.com/wannesm/leuvenmapmatching
    - gpx-converter
