name: thesis-environment

dependencies:
  - ipywidgets=8.0.4
  - IPython
  - libspatialindex
  - voila
  - pip
  - pip:
    - git+https://github.com/wannesm/leuvenmapmatching
    - gpx-converter==2.1.0
    - numpy==1.23.0
    - pyproj==3.5.0
    - geopandas==0.13.0
    - shapely==2.0.1
    - osmnx==1.3.0
    - fiona==1.9.4
    - rtree==1.0.1
    - mapclassify==2.5.0
    - leafmap==0.20.3
