name: thesis-environment

dependencies:
  - ipywidgets=7.7.1
  - IPython=7.34.0
  - numpy=1.23.0
  - pyproj=3.5.0
  - geopandas=0.13.0
  - shapely=2.0.1
  - osmnx=1.3.0
  - fiona=1.9.4
  - rtree=1.0.1
  - mapclassify=2.5.0
  - leafmap=0.20.3
  - libspatialindex=1.9.3
  - voila=0.4.0
  - pip=23.1.2
  - pip:
    - git+https://github.com/wannesm/leuvenmapmatching
    - gpx-converter==2.1.0
